sudo: required

language: go

services:
  - docker

go:
  - "1.10.x"

script:
  - make ci-coverage
  - make integration-tests

after_success:
  # send coverage report to codecov
  - bash <(curl -s https://codecov.io/bash)