sudo: required

language: go

services:
  - docker

go:
  - master

before_install:
  # install dep
  - go get -u github.com/golang/dep/cmd/dep
  # install goveralls
  - go get github.com/mattn/goveralls
  # this stays after the above goes away
  - dep ensure -v
  - docker build -t api_test -f test.Dockerfile .

script:
  # unit tests
  - docker run --name api_test --rm api_test
  # integration tests
  - docker-compose --file integration_tests.yml up --abort-on-container-exit --build --remove-orphans --force-recreate
  # coverage output
  - go test github.com/dairycart/dairycart/api -coverprofile=coverage.out -parallel=1

after_success:
  # send coverage report to coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN