sudo: required

language: go

services:
  - docker

go:
  - master

before_install:
  - docker build -t api_test -f api/test.Dockerfile .

script:
  - docker run --name api_test --rm api_test
  - docker-compose --file docker-compose-test.yml up --abort-on-container-exit --build --remove-orphans --force-recreate

# after_success:
#   - bash <(curl -s https://codecov.io/bash)