sudo: required

install:
  -

language: go

services:
  - docker

go:
  - master

before_install:
  # install dep
  - go get -u github.com/golang/dep/cmd/dep
  # install goveralls
  - go get github.com/mattn/goveralls
  # install dependencies
  - dep ensure -v
  # build relevant dockerfiles
  - docker build -t api_test -f test.Dockerfile .
  # remove this once we build a makefile
  - docker build -t plugins --file plugin.Dockerfile .


script:
  # remove this once we build a makefile
  - docker run --volume=$GOPATH/src/github.com/dairycart/dairycart/api/example_files/plugins:/output --rm -t plugins
  - ls $GOPATH/src/github.com/dairycart/dairycart/api/example_files/plugins
  # unit tests
  - docker run --name api_test --rm api_test
  # integration tests
  - docker-compose --file integration_tests.yml up --abort-on-container-exit --build --remove-orphans --force-recreate
  # coverage output
  - go test github.com/dairycart/dairycart/api -coverprofile=coverage.out -parallel=1

after_success:
  # send coverage report to coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN