sudo: required

language: go

services:
  - docker

go:
  - "1.10.x"

before_install:
  # install dep
  - go get -u github.com/golang/dep/cmd/dep
  # install goveralls
  - go get github.com/mattn/goveralls
  # install dependencies
  - dep ensure -v

script:
  - make tests
  - make ci-coverage

after_success:
  # send coverage report to coveralls
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN