# build stage
FROM golang:alpine AS build-stage
WORKDIR /go/src/github.com/verygoodsoftwarenotvirus/dairycart/migrations

RUN pwd

ADD vendor vendor
ADD ./migrations ./migrations
WORKDIR ./migrations
RUN go build -o /migrator
# RUN ls

# final stage
from postgres:9.6-alpine

COPY --from=build-stage /migrator migrator
# ENV DAIRYCART_DB_URL=postgres://ockhafwg:RDqIgwY_OZl6F2IKZzmGK3fG1AjRBD8B@stampy.db.elephantsql.com:5432/ockhafwg
ENV DAIRYCART_DB_URL=postgres://username:password@localhost/dairycart
CMD ["postgres"]
CMD ["/migrator", "init"]
CMD ["/migrator"]