version: '3.2'

services:
  dairycart:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
    links:
      - database
    environment:
      DAIRYCART_MIGRATIONS_DIR: "file:///migrations"
      DAIRYCART_DB_URL: postgres://dairycart:password@database:5432/dairycart?sslmode=disable
  database:
    image: postgres:alpine
    ports:
    - '2345:5432'
    environment:
      POSTGRES_USER: dairycart
      POSTGRES_PASSWORD: password