# build stage
FROM golang:alpine AS build-stage
WORKDIR /go/src/github.com/verygoodsoftwarenotvirus/dairycart/migrations

RUN pwd

ADD vendor vendor
ADD ./migrations ./migrations
WORKDIR ./migrations
RUN go build -o /migrator
# RUN ls

# final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates

COPY --from=build-stage /migrator migrator
ENV DAIRYCART_DB_URL=postgres://username:password@localhost/dairycart
CMD ["/migrator", "init"]
CMD ["/migrator"]