version: "3.3"

services:
  database:
    image: postgres:latest
    ports:
    - "2345:5432"
    environment:
      - POSTGRES_USER=dairycart
      - POSTGRES_PASSWORD=hunter2
    # logging:
    #   driver: none

  api:
    build:
      context: .
      dockerfile: dockerfiles/main.Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - database
    links:
      - database

 admin:
   build:
     context: admin
     dockerfile: dockerfiles/admin.Dockerfile
   ports:
     - "1234:1234"
   links:
     - api
   depends_on:
     - api
   environment:
     - VIRTUAL_HOST=admin.dairycart.com
     - DAIRYCART_API_URL=http://api:4321

 nginx-proxy:
   image: jwilder/nginx-proxy
   ports:
     - "80:80"
   depends_on:
     - admin
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro