version: "3.2"

services:
  database:
    image: postgres:alpine
    ports:
    - "2345:5432"
    environment:
      - POSTGRES_USER=dairycart
      - POSTGRES_PASSWORD=hunter2
    # logging:
    #   driver: none

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - database
    links:
      - database
    environment:
      - DB_TO_USE=postgres
      - VIRTUAL_HOST=api.dairycart.com
      - DAIRYCART_MIGRATIONS_DIR=file:///migrations
      - DAIRYCART_DB_URL=postgres://dairycart:hunter2@database:5432/dairycart?sslmode=disable

#  admin:
#    build:
#      context: admin
#      dockerfile: Dockerfile
#    ports:
#      - "1234:1234"
#    links:
#      - api
#    depends_on:
#      - api
#    environment:
#      - VIRTUAL_HOST=admin.dairycart.com
#      - DAIRYCART_API_URL=http://api:4321
#
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#      - "80:80"
#    depends_on:
#      - admin
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro