# Example Dairycart configuration

port = 4321
migrate_example_data = false

[database]
type = "postgres"
connection_details = "postgres://dairycart:hunter2@database:5432/dairycart?sslmode=disable"

[image_storage]
type = "local"
base_url = "http://localhost"
