version: "3.2"

services:
  database:
    image: postgres:alpine
    ports:
    - "2345:5432"
    environment:
      POSTGRES_USER: dairytest
      POSTGRES_PASSWORD: hunter2
    logging:
      driver: "none"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - database
    links:
      - database
    environment:
      DB_TO_USE: "postgres"
      MIGRATE_EXAMPLE_DATA: "YES"
      DAIRYCART_MIGRATIONS_DIR: "file:///migrations"
      DAIRYCART_DB_URL: postgres://dairytest:hunter2@database:5432/dairytest?sslmode=disable
    logging:
      driver: "none"

  httpbin:
    image: kennethreitz/httpbin:latest
    ports:
    - "80:8080"
    logging:
      driver: "none"

  test:
    build:
      context: integration_tests
      dockerfile: Dockerfile
    links:
      - api
      - httpbin
    environment:
      INTEGRATION_API_URL: http://api:4321
      DAIRYCART_DB_URL: postgres://dairytest:hunter2@database:5432/dairytest?sslmode=disable
