version: "3.3"

services:
  database:
    image: postgres:latest
    ports:
    - "2345:5432"
    environment:
      POSTGRES_USER: dairytest
      POSTGRES_PASSWORD: hunter2
    logging:
      driver: "none"

  api:
    build:
      context: ../
      dockerfile: dockerfiles/integration-server.Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - database
    links:
      - database
    logging:
      driver: "none"

  gen:
    build:
      context: ../
      dockerfile: dockerfiles/storage-generation.Dockerfile
    links:
      - api
    environment:
      DAIRYCART_API_URL: http://api:4321
      DAIRYCART_DB_URL: postgres://dairytest:hunter2@database:5432/dairytest?sslmode=disable
    volumes:
      - type: bind
        source: $GOPATH/src/github.com/dairycart/dairycart/storage/v1/database
        target: /go/src/github.com/dairycart/dairycart/storage/v1/database
