INSERT INTO products
(
    "name",
    "subtitle",
    "description",
    "sku",
    "upc",
    "manufacturer",
    "brand",
    "quantity",
    "taxable",
    "price",
    "on_sale",
    "sale_price",
    "cost",
    "product_weight",
    "product_height",
    "product_width",
    "product_length",
    "package_weight",
    "package_height",
    "package_width",
    "package_length",
    "quantity_per_package"
)
VALUES
(
    /* name                 */ 'Your Favorite Band''s T-Shirt',
    /* subtitle             */ 'A t-shirt you can wear',
    /* description          */ 'Wear this if you''d like. Or don''t, I''m not in charge of your actions',
    /* sku                  */ 't-shirt',
    /* upc                  */ null,
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Your Favorite Band',
    /* quantity             */ 666,
    /* taxable              */ 'true',
    /* price                */ 20.00,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 10,
    /* product_weight       */ 1,
    /* product_height       */ 5,
    /* product_width        */ 5,
    /* product_length       */ 5,
    /* package_weight       */ 1,
    /* package_height       */ 5,
    /* package_width        */ 5,
    /* package_length       */ 5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Sleeping People - Sleeping People',
    /* subtitle             */ 'A solid math rock album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'sleeping-people',
    /* upc                  */ '656605908410',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Sleeping People',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Jaga Jazzist - One Armed Bandit',
    /* subtitle             */ 'A solid jazz album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'one-armed-bandit',
    /* upc                  */ '5021392578187',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Jaga Jazzist',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Cloudkicker - Let Yourself Be Huge',
    /* subtitle             */ 'A solid instrumental album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'let-yourself-be-huge',
    /* upc                  */ null,
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Cloudkicker',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Animals As Leaders - The Joy Of Motion',
    /* subtitle             */ 'A solid prog metal album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'the-joy-of-motion',
    /* upc                  */ '817424013895',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Animals As Leaders',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Mort Garson - Mother Earth''s Plantasia',
    /* subtitle             */ 'A solid synth album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'mother-earths-plantasia',
    /* upc                  */ '5291103812552',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Mort Garson',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Camel - The Snow Goose',
    /* subtitle             */ 'A solid prog rock album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'the-snow-goose',
    /* upc                  */ '600753356661',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Camel',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Piglet - Lava Land',
    /* subtitle             */ 'Another solid math rock album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'lava-land',
    /* upc                  */ null,
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Piglet',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Tera Melos - Untitled',
    /* subtitle             */ 'Yet another solid math rock album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'untitled',
    /* upc                  */ '634457550513',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Tera Melos',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'Frank Zappa - Jazz From Hell',
    /* subtitle             */ 'A solid Zappa album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'jazz-from-hell',
    /* upc                  */ '013347420516',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'Frank Zappa',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
),
(
    /* name                 */ 'CHON - Newborn Sun',
    /* subtitle             */ 'Yet another solid math rock album',
    /* description          */ 'Arbitrary description can go here because real product descriptions are technically copywritten.',
    /* sku                  */ 'newborn-sun',
    /* upc                  */ '794558090315',
    /* manufacturer         */ 'Record Company',
    /* brand                */ 'CHON',
    /* quantity             */ 123,
    /* taxable              */ 'true',
    /* price                */ 12.34,
    /* on_sale              */ 'false',
    /* sale_price           */ 0.00,
    /* cost                 */ 5,
    /* product_weight       */ 1,
    /* product_height       */ 12,
    /* product_width        */ 12,
    /* product_length       */ .5,
    /* package_weight       */ 1,
    /* package_height       */ 12,
    /* package_width        */ 12,
    /* package_length       */ .5,
    /* quantity_per_package */ 1
);

INSERT INTO product_options
(
    "name",
    "product_id"
)
VALUES
('color', 1),
('size', 1);

INSERT INTO product_option_values
(
    "product_option_id",
    "value"
)
VALUES
(1, 'red'),
(1, 'green'),
(1, 'blue'),
(2, 'small'),
(2, 'medium'),
(2, 'large');

INSERT INTO discounts
(
    "name",
    "type",
    "amount",
    "starts_on",
    "expires_on"
)
VALUES
(
    '10% off',
    'percentage',
    10.00,
    NOW(),
    NOW() + (1 * interval '1 month')
),
(
    '50% off',
    'percentage',
    50.00,
    NOW(),
    null
),
(
    'New customer special',
    'flat_amount',
    10.00,
    NOW(),
    null
);